// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC63CwYeuxzKwfR5iNqqAeOKgbz5ZCv6-g',
    appId: '1:977918486336:web:b59040a6ae4a51df8f7ca5',
    messagingSenderId: '977918486336',
    projectId: 'course-app-tourism',
    authDomain: 'course-app-tourism.firebaseapp.com',
    storageBucket: 'course-app-tourism.appspot.com',
    measurementId: 'G-MKFSMRBG4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS5ms5aaxiTzJxOHtHEDPjZX_rXg1cAs0',
    appId: '1:977918486336:android:85af95b94692b93b8f7ca5',
    messagingSenderId: '977918486336',
    projectId: 'course-app-tourism',
    storageBucket: 'course-app-tourism.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2SIau5VNCQU5pFaN1-GtdwN-t4j38grA',
    appId: '1:977918486336:ios:5cc63a5e5b6f80c58f7ca5',
    messagingSenderId: '977918486336',
    projectId: 'course-app-tourism',
    storageBucket: 'course-app-tourism.appspot.com',
    iosClientId: '977918486336-0mknlqnug85k5bmr12ejtluqtq3t7fp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTourism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2SIau5VNCQU5pFaN1-GtdwN-t4j38grA',
    appId: '1:977918486336:ios:68ccf159006b22e98f7ca5',
    messagingSenderId: '977918486336',
    projectId: 'course-app-tourism',
    storageBucket: 'course-app-tourism.appspot.com',
    iosClientId: '977918486336-atc2jh9l0eucd7b4bted3261j1u1132l.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTourism.RunnerTests',
  );
}
